#!/bin/sh

# NONAMETV=nonametv-import
NONAMETV="tools/nonametv-import"

$NONAMETV Axess $1 $2 $3
$NONAMETV Arte $1 $2 $3
$NONAMETV BBCWorld $1 $2 $3
$NONAMETV BBCWW $1 $2 $3
$NONAMETV CanalPlus $1 $2 $3
$NONAMETV Discovery_xml $1 $2 $3
$NONAMETV DR $1 $2 $3
$NONAMETV DreiSat $1 $2 $3
$NONAMETV Eurosport $1 $2 $3
$NONAMETV Infomedia $1 $2 $3
$NONAMETV Kanal5 $1 $2 $3
$NONAMETV Kanal9 $1 $2 $3
$NONAMETV Mtve $1 $2 $3
$NONAMETV Nonstop $1 $2 $3
$NONAMETV NonstopWeekly $1 $2 $3
$NONAMETV NRK $1 $2 $3
$NONAMETV ORF $1 $2 $3
$NONAMETV SverigesRadio $1 $2 $3
$NONAMETV Svt $1 $2 $3
$NONAMETV Viasat $1 $2 $3
$NONAMETV TV4 $1 $2 $3
$NONAMETV TVP $1 $2 $3
$NONAMETV ZDF $1 $2 $3
$NONAMETV ZoneReality $1 $2 $3
