#!/bin/bash

NROOT=/var/local/nonametv
PROOT=/home/beatx/github/nonametv/

#Q="--quiet --quiet"
Q="--verbose --force-update"
F="--force-update"

h=true
d=true

cd $PROOT

if [ $1x = --weeklyx ]
then
  # Run weekly commands.
  perl -I lib tools/nonametv-remove-old
  tools/se/nonametv-import-allhttp --remove-old

  # Move away old files  after 6 weeks
  tools/nonametv-filestore-moveold --all --leavedays 42
  exit
fi

if [ $1x = --dailyx ]
then
  # Run daily commands
  d=
fi

if [ $1x = --hourlyx ]
then
  # Run hourly commands
  h=
fi


# This runs by cronjob - seperately
#tools/se/nonametv-process-mail

$d tools/se/nonametv-import-allhttp $Q
$h tools/se/nonametv-import-allhttp $Q --short-grab
tools/se/nonametv-import-allmail $Q

$d perl -I lib/ tools/nonametv-export Xmltv --remove-old
$d perl -I lib/ tools/nonametv-export Json --remove-old
$d tools/nonametv-icon-update --quiet --unattended

tools/se/nonametv-updatesite $Q

# This shouldn't produce any output, but there seems to be a bug
# somewhere.
$d perl -I lib tools/nonametv-export Xmltv --force-export --verbose 

# Run hourly export
#$h perl -I lib tools/nonametv-export Xmltv --verbose
#$h perl -I lib tools/nonametv-export Json --verbose

# Update the Downconverter-channels as well.
$d perl -I lib tools/nonametv-import Downconverter $Q
$h perl -I lib tools/nonametv-import Downconverter --short-grab $Q

# Update the Combiner-channels as well.
#$d perl -I lib tools/nonametv-import Combiner $Q
#$h perl -I lib tools/nonametv-import Combiner --short-grab $Q

perl -I lib tools/nonametv-batchlog > $NROOT/html/00status.html

tools/se/nonametv-updatesite $Q
$d tools/se/nonametv-xmltv-compare-run

# Run after, everything
$d rsync -rsh=ssh --delete /var/local/nonametv/html/00status.html tvzon:/var/www/xmltv/