#!/bin/sh

NROOT=/var/local/nonametv
SC_OPT=-qq
V=false

if [ $1z = '--verbosez' ]
then
  SC_OPT=
  V=true
fi
$V && echo "Local rsync"
rsync -c --delete -r $NROOT/xmltv_staging/ $NROOT/xmltv/
tools/se-tvzon/nonametv-xmltv-gendatalist
rsync -c --delete -r $NROOT/json_extra_staging/ $NROOT/json_extra/
#tools/se-tvzon/nonametv-xmltv-extra-gendatalist
rsync -c --delete -r $NROOT/xmltv_staging_iso/ $NROOT/xmltv_iso/
rsync -c --delete -r $NROOT/json_staging/ $NROOT/json/

$V && echo "tvzon"
#sitecopy --update $SC_OPT tvzon

tools/nonametv-upload xmltv1 
