#!/bin/sh

NROOT=/var/local/nonametv

#tools/nonametv-export Xmltv --export-channels $1 $2 $3
#tools/nonametv-export Xmltv $1 $2 $3
#/home/jnylen/projects/convert_jsontv/runny
#tools/nonametv-export Xmltv2 --export-channels $1 $2 $3
#tools/nonametv-export Xmltv2 $1 --force-export $3
tools/nonametv-export Json_extra --export-channels $1 $2 $3
tools/nonametv-export Json_extra $1 --force-export $3
tools/nonametv-export Json --export-channels $1 $2 $3
tools/nonametv-export Json $1 --force-export $3

tools/nonametv-export Json --export-channels --channel-group TV
tools/nonametv-export Json --export-channels --channel-group RADIO
tools/nonametv-export Json --export-channels --channel-group DEV
tools/nonametv-export Json --export-channels --channel-group Norway
tools/nonametv-export Json --export-channels --channel-group Sweden
tools/nonametv-export Json --export-channels --channel-group Finland
tools/nonametv-export Json --export-channels --channel-group Denmark
tools/nonametv-export Json --export-channels --channel-group Netherlands
tools/nonametv-export Json --export-channels --channel-group Germany
tools/nonametv-export Json --export-channels --channel-group Austria
tools/nonametv-export Json --export-channels --channel-group Switzerland

# Channel group channels.xml.gz (Should we add it to respective channel owner?)
#tools/nonametv-export Xmltv --export-channels --channel-group TV
#tools/nonametv-export Xmltv --export-channels --channel-group RADIO
#tools/nonametv-export Xmltv --export-channels --channel-group DEV
#tools/nonametv-export Xmltv2 --export-channels --channel-group TV
#tools/nonametv-export Xmltv2 --export-channels --channel-group RADIO
#tools/nonametv-export Xmltv2 --export-channels --channel-group DEV
#tools/nonametv-export Xmltv_extra --export-channels --channel-group TV
#tools/nonametv-export Xmltv_extra --export-channels --channel-group RADIO
#tools/nonametv-export Xmltv_extra --export-channels --channel-group DEV

# XMLTV UTF8
#tools/se-tvzon/nonametv-xmltv-genhtml $NROOT/xmltv_staging
#tools/nonametv-localize-movies > $NROOT/xmltv_staging/00movies.html
#rsync examples/displayfile.html $NROOT/xmltv_staging
#rsync examples/listing.xsl $NROOT/xmltv_staging

# XMLTV ISO
tools/se-tvzon/nonametv-xmltv-genhtml $NROOT/xmltv_staging_iso/
rsync examples/displayfile.html $NROOT/xmltv_staging_iso/
rsync examples/listing.xsl $NROOT/xmltv_staging_iso/

# XMLTV Extra
#tools/se-tvzon/nonametv-xmltv-genhtml $NROOT/xmltv_extra_staging/
#rsync examples/displayfile.html $NROOT/xmltv_extra_staging/
#rsync examples/listing.xsl $NROOT/xmltv_extra_staging/
