#!/bin/sh

# NONAMETV=nonametv-import
NONAMETV="tools/nonametv-import"

$NONAMETV AFN $1 $2 $3
$NONAMETV Axess $1 $2 $3
$NONAMETV Arte $1 $2 $3
$NONAMETV BBCWorld $1 $2 $3
$NONAMETV Bleb $1 $2 $3
#$NONAMETV BBCWW $1 $2 $3
$NONAMETV CMore $1 $2 $3
$NONAMETV CMoreDK $1 $2 $3
$NONAMETV CMoreNO $1 $2 $3
#$NONAMETV CanalPlus $1 $2 $3
$NONAMETV Discovery_xml $1 $2 $3
$NONAMETV DR $1 $2 $3
$NONAMETV DK4 $1 $2 $3
$NONAMETV DreiSat $1 $2 $3
$NONAMETV DasErste $1 $2 $3
$NONAMETV Eurosport $1 $2 $3
$NONAMETV Infomedia $1 $2 $3
$NONAMETV Kanal5 $1 $2 $3
$NONAMETV Kanal9 $1 $2 $3
$NONAMETV KanalGlobal $1 $2 $3
$NONAMETV MTVde $1 $2 $3
$NONAMETV Mtve $1 $2 $3
$NONAMETV Nonstop $1 $2 $3
$NONAMETV Nonstop2 $1 $2 $3
$NONAMETV NRK $1 $2 $3
$NONAMETV ORF $1 $2 $3
$NONAMETV RadioSeven $1 $2 $3
$NONAMETV SBSRadio $1 $2 $3
$NONAMETV SBSTV $1 $2 $3
$NONAMETV SverigesRadio $1 $2 $3
$NONAMETV Svt $1 $2 $3
$NONAMETV Viasat $1 $2 $3
$NONAMETV ViasatNO $1 $2 $3
$NONAMETV TV2 $1 $2 $3
$NONAMETV TV2NO $1 $2 $3
$NONAMETV TV4 $1 $2 $3
$NONAMETV TVP $1 $2 $3
$NONAMETV TVNorge $1 $2 $3
$NONAMETV ZDF $1 $2 $3
$NONAMETV ZoneReality $1 $2 $3
$NONAMETV HRT $1 $2 $3

# This isnt really working, it airs
# programmes at the same time sometimes.
#$NONAMETV Unibet $1 $2 $3
