#!/bin/bash

NROOT=/var/local/nonametv
PROOT=/home/jnylen/projects/nonametv/

#Q="--quiet --quiet"
Q="--verbose"
F="--force-update"

h=true
d=true
one=true

cd $PROOT

if [ $1x = --weeklyx ]
then
  # Run weekly commands.
  perl -I lib tools/nonametv-remove-old
  tools/se-tvzon/nonametv-import-allhttp --remove-old

  # Move away old files  after 6 weeks
  tools/nonametv-filestore-moveold --all --leavedays 42

  # Remove old files after 70 days (safes space)
  tools/nonametv-filestore-removeold --all --leavedays 70
  
  # remove Tvrage cache (they can't be updated automatic..
  # .. as tvrage doesnt provide that sort of system)
  rm /storage/nonametv/contentcache/Tvrage/tvrage.db

  # Make sure we have all xmltv updated. As some seem to go missing (Somehow)
  # (for example if the time on the server is way off)
  tools/nonametv-export Xmltv --force-export
  tools/nonametv-export Json --force-export
  
  # Remove old programmes and batches
  perl -I lib tools/nonametv-remove-old

  exit
fi

if [ $1x = --dailyx ]
then
  # Run daily commands
  d=
fi

if [ $1x = --onex ]
then
  # Run 13.00 commands
  one=
fi

if [ $1x = --hourlyx ]
then
  # Run hourly commands
  h=
fi


# This runs by cronjob - seperately
#tools/se-tvzon/nonametv-process-mail

# Update tvdb
$d perl -I lib tools/nonametv-update-tvdb sv
$d perl -I lib tools/nonametv-update-tvdb en
$d perl -I lib tools/nonametv-update-tvdb de
$d perl -I lib tools/nonametv-update-tvdb no

# Import everything
$d tools/se-tvzon/nonametv-import-allhttp $Q
$h tools/se-tvzon/nonametv-import-allhttp $Q --short-grab
#tools/se-tvzon/nonametv-import-allmail $Q

# Remove old
$d perl -I lib/ tools/nonametv-export Xmltv --remove-old
$d perl -I lib/ tools/nonametv-export Xmltv2 --remove-old
$d perl -I lib/ tools/nonametv-export Json_extra --remove-old
$d perl -I lib/ tools/nonametv-export Json --remove-old
$d tools/nonametv-icon-update --quiet --unattended

# Export
tools/se-tvzon/nonametv-updatesite $Q

# Upload to www - I don't know if I wanna run this here.
tools/se-tvzon/nonametv-upload $Q

# This shouldn't produce any output, but there seems to be a bug
# somewhere.
$d perl -I lib tools/nonametv-export Xmltv --force-export --verbose 

# Update the Combiner-channels as well.
$d perl -I lib tools/nonametv-import Combiner $Q
$h perl -I lib tools/nonametv-import Combiner --short-grab $Q

# Update the Downconverter-channels as well.
$d perl -I lib tools/nonametv-import Downconverter $Q
$h perl -I lib tools/nonametv-import Downconverter --short-grab $Q

# Batchlog
$d perl -I lib tools/nonametv-batchlog > $NROOT/html/00status.html

# Export
tools/se-tvzon/nonametv-updatesite $Q

# Compare
$d tools/se-tvzon/nonametv-xmltv-compare-run

# Upload to www (daily)
$d tools/se-tvzon/nonametv-upload $Q

# Upload to www (at 13.00)
$h tools/se-tvzon/nonametv-upload $Q

# Run after, everything
$d rsync --delete -r /var/local/nonametv/html/00status.html /var/www/xmltv/
$d rsync --delete -r /var/local/nonametv/xmltv_compare/ /var/www/xmltv/compare/

# Some users seems to download this file from the base url instead, this will fix it.
$d rsync --delete -r /var/local/nonametv/xmltv/channels.xml.gz /var/www/xmltv/
