#!/bin/bash

tools/nonametv-import CNBC $1 $2 $3
tools/nonametv-import Discovery $1 $2 $3
tools/nonametv-import DisneyChannel $1 $2 $3
tools/nonametv-import DisneyChannelNO $1 $2 $3
tools/nonametv-import DisneyChannelDK $1 $2 $3
tools/nonametv-import DWDE $1 $2 $3
tools/nonametv-import Kanal10 $1 $2 $3
tools/nonametv-import Motors $1 $2 $3
tools/nonametv-import Mtve_mail $1 $2 $3
tools/nonametv-import NatGeoWild $1 $2 $3
tools/nonametv-import PokerChannel $1 $2 $3
tools/nonametv-import History $1 $2 $3
tools/nonametv-import TravelChannel $1 $2 $3
tools/nonametv-import God $1 $2 $3
tools/nonametv-import Gospel $1 $2 $3
tools/nonametv-import TVChile $1 $2 $3
tools/nonametv-import Svt $1 $2 $3
tools/nonametv-import Venetsia $1 $2 $3
tools/nonametv-import SBSTVSWE $1 $2 $3
tools/nonametv-import BBCWW $1 $2 $3
tools/nonametv-import ChannelOneRussia $1 $2 $3
tools/nonametv-import WFC $1 $2 $3

# Porn
tools/nonametv-import HustlerTV $1 $2 $3
tools/nonametv-import Playboy $1 $2 $3

tools/nonametv-import LifestyleTV $1 $2 $3
tools/nonametv-import FuelTV $1 $2 $3
tools/nonametv-import Fatstone $1 $2 $3
tools/nonametv-import France24 $1 $2 $3
tools/nonametv-import LuxeTV $1 $2 $3
tools/nonametv-import Mezzo $1 $2 $3
tools/nonametv-import HighTV $1 $2 $3
tools/nonametv-import HaC $1 $2 $3

# Boomerang and Cartoon network
tools/nonametv-import Turner_doc $1 $2 $3
tools/nonametv-import VH1Classic $1 $2 $3

tools/nonametv-import Euronews $1 $2 $3
tools/nonametv-import RTL2 $1 $2 $3
tools/nonametv-import Ginx $1 $2 $3

tools/nonametv-import Turner $1 $2 $3
tools/nonametv-import TV8Norge $1 $2 $3

tools/nonametv-import Motors $1 $2 $3
tools/nonametv-import YaS $1 $2 $3
