#!/bin/bash

NROOT=/var/local/nonametv
PROOT=/home/beatx/github/nonametv/

#Q="--quiet --quiet"
Q="--verbose"
F="--force-update"

h=true
d=true
one=true

cd $PROOT

if [ $1x = --weeklyx ]
then
  # Run weekly commands.
  perl -I lib tools/nonametv-remove-old
  tools/se-tvzon/nonametv-import-allhttp --remove-old

  # Move away old files  after 6 weeks
  tools/nonametv-filestore-moveold --all --leavedays 42

  # remove Tvdb cache, updates seem to be broken at the moment
  rm $NROOT/contentcache/Tvdb/tvdb.db

  exit
fi

if [ $1x = --dailyx ]
then
  # Run daily commands
  d=
fi

if [ $1x = --onex ]
then
  # Run 13.00 commands
  one=
fi

if [ $1x = --hourlyx ]
then
  # Run hourly commands
  h=
fi


# This runs by cronjob - seperately
#tools/se-tvzon/nonametv-process-mail

# Import everything
$d tools/se-tvzon/nonametv-import-allhttp $Q
$h tools/se-tvzon/nonametv-import-allhttp $Q --short-grab
tools/se-tvzon/nonametv-import-allmail $Q

# Remove old
$d perl -I lib/ tools/nonametv-export Xmltv --remove-old
$d perl -I lib/ tools/nonametv-export Xmltv2 --remove-old
$d perl -I lib/ tools/nonametv-export Json --remove-old
$d tools/nonametv-icon-update --quiet --unattended

# Export
tools/se-tvzon/nonametv-updatesite $Q

# Upload to www - I don't know if I wanna run this here.
#tools/se-tvzon/nonametv-upload $Q

# This shouldn't produce any output, but there seems to be a bug
# somewhere.
$d perl -I lib tools/nonametv-export Xmltv --force-export --verbose 

# Update the Downconverter-channels as well.
$d perl -I lib tools/nonametv-import Downconverter $Q
$h perl -I lib tools/nonametv-import Downconverter --short-grab $Q

# Batchlog
$d perl -I lib tools/nonametv-batchlog > $NROOT/html/00status.html

# Export
tools/se-tvzon/nonametv-updatesite $Q

# Compare
$d tools/se-tvzon/nonametv-xmltv-compare-run

# Upload to www (daily)
$d tools/se-tvzon/nonametv-upload $Q

# Upload to www (at 13.00)
$one tools/se-tvzon/nonametv-upload $Q

# Run after, everything
$d rsync -rsh=ssh --delete /var/local/nonametv/html/00status.html tvzon:/var/www/xmltv/
