#!/usr/bin/perl -w

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../../lib";

use Mail::Box;
use Mail::Box::Manager;

my $maildir = "/home/jnylen/maildir/";
my $infoldername = ".Projects/xmltv-data-in";
my $targetprefix = ".Projects/.NonameTV-Data.";

my $folders;

my $mgr = Mail::Box::Manager->new();

my $rootfolder = $mgr->open( type => 'maildir', folder => $maildir );
#my @subs = $rootfolder->listSubFolders();
#print join "\n", @subs;

my $infolder = $rootfolder->openSubFolder( $infoldername, access => 'rw' );

foreach my $msg ($infolder->messages) {
  next if $msg->isDeleted();
  my @from = $msg->from;
  my $fromaddr = $from[0]->format;
  if( $fromaddr =~ /\@dr.dk/ ) {
    MoveMessage( $msg, "DR" );
  }
  elsif( $fromaddr =~ /millenniumgroup.se/i ) {
    # Matches both @millenniumgroup.se and 
    # millenniumgroup.se@bounce.maildirect.se
    MoveMessage( $msg, "Nonstop" );
  }
  elsif( $fromaddr =~ /\@mtvne.com/i ) {
    MoveMessage( $msg, "MTV" );
  }
  elsif( $fromaddr =~ /\@tv7games.se/ ) {
    MoveMessage( $msg, "TV7" );
  }
  elsif( $fromaddr =~ /\@tv3.se/i ) {
    MoveMessage( $msg, "Viasat" );
  }
  elsif( $fromaddr =~ /\@viasat.se/i ) {
    MoveMessage( $msg, "Viasat" );
  }
  elsif( $fromaddr =~ /\@viasat.co.uk/i ) {
    MoveMessage( $msg, "Viasat" );
  }
  elsif( $fromaddr =~ /\@mtg.se/i ) {
    MoveMessage( $msg, "Viasat" );
  }
  elsif( $fromaddr =~ /\@mtgtv.se/i ) {
    MoveMessage( $msg, "Viasat" );
  }
  elsif( $fromaddr =~ /\@disney.com/i ) {
    MoveMessage( $msg, "Disney" );
  }
  elsif( $fromaddr =~ /\@googlemail.com/i ) {
    MoveMessage( $msg, "Gmail" );
  }
  elsif( $fromaddr =~ /\@france24.com/i ) {
    MoveMessage( $msg, "France24" );
  }
  elsif( $fromaddr =~ /\@playboytv.co.uk/i ) {
    MoveMessage( $msg, "Playboy" );
  }
  elsif( $fromaddr =~ /\@playboy.com/i ) {
    MoveMessage( $msg, "Playboy" );
  }
  elsif( $fromaddr =~ /\@playboyplus.com/i ) {
    MoveMessage( $msg, "Playboy" );
  }
  elsif( $fromaddr =~ /\@sapphiremedia.com/i ) {
    MoveMessage( $msg, "Hustler" );
  }
  elsif( $fromaddr =~ /\@globallistings.info/i ) {
    MoveMessage( $msg, "GlobalListings" );
  }
  elsif( $fromaddr =~ /\@kanal10.se/i ) {
    MoveMessage( $msg, "Kanal10" );
  }
  elsif( $fromaddr =~ /\@oppnakanalengoteborg.se/i ) {
    MoveMessage( $msg, "OKGoteborg" );
  }
  elsif( $fromaddr =~ /\@nauticalchannel.net/i ) {
    MoveMessage( $msg, "YaS" );
  }
  elsif( $fromaddr =~ /\@motorstv.com/i ) {
    MoveMessage( $msg, "Motors" );
  }
  elsif( $fromaddr =~ /\@chellozone.com/i ) {
    MoveMessage( $msg, "Chellozone" );
  }
  elsif( $fromaddr =~ /\@svt.se/i ) {
    #MoveMessage( $msg, "Svt" );
  }
  elsif( $fromaddr =~ /\@fox.com/i ) {
    MoveMessage( $msg, "FOX" );
  }
  elsif( $fromaddr =~ /\@cnbc.com/i ) {
    MoveMessage( $msg, "CNBC" );
  }
  elsif( $fromaddr =~ /\@out.tv/i ) {
    MoveMessage( $msg, "OUTTV" );
  }
  elsif( $fromaddr =~ /\@tv5monde.org/i ) {
    MoveMessage( $msg, "TV5Monde" );
  }
  elsif( $fromaddr =~ /\@travelchannel.co.uk/i ) {
    MoveMessage( $msg, "TravelChannel" );
  }
  elsif( $fromaddr =~ /\@turner.com/i ) {
    MoveMessage( $msg, "Turner" );
  }
  elsif( $fromaddr =~ /\@espnamerica.com/i ) {
    MoveMessage( $msg, "ESPN" );
  }
  elsif( $fromaddr =~ /\@pokerchanneleurope.com/i ) {
    MoveMessage( $msg, "PokerChannel" );
  }
  elsif( $fromaddr =~ /\@lifestyletv.se/i ) {
    MoveMessage( $msg, "LifestyleTV" );
  }
  elsif( $fromaddr =~ /\@tvn.cl/i ) {
    MoveMessage( $msg, "TVChile" );
  }
  elsif( $fromaddr =~ /\@fyc.pt/i ) {
    MoveMessage( $msg, "FuelTV" );
  }
  elsif( $fromaddr =~ /\@luxe.tv/i ) {
    MoveMessage( $msg, "LuxeTV" );
  }
  elsif( $fromaddr =~ /\@god.tv/i ) {
    MoveMessage( $msg, "GodTV" );
  }
  
  
  elsif( $fromaddr =~ /\@tvzon.se/i ) {
    MoveMessage( $msg, "LuxeTV" );
  }
}

sub MoveMessage {
  my( $msg, $foldername ) = @_;

  if( not exists $folders->{$foldername} ) {
    $folders->{$foldername} = 
	$rootfolder->openSubFolder( $targetprefix . $foldername, 
				    access => 'rw' );
  }

  $msg->moveTo( $folders->{$foldername} );
}
