#!/bin/sh

NROOT=/home/nonametv/var
PROOT=/home/nonametv/nonametv

Q="--quiet --quiet"

h=true
d=true

cd $PROOT

if [ $1x = --weeklyx ]
then
  # Run weekly commands.
  perl -I lib tools/nonametv-remove-old
  tools/de/nonametv-import-allhttp --remove-old
  exit
fi

if [ $1x = --dailyx ]
then
  # Run daily commands
  d=
fi

if [ $1x = --hourlyx ]
then
  # Run hourly commands
  h=
fi

#tools/de/nonametv-process-mail

$d tools/de/nonametv-import-allhttp $Q
$h tools/de/nonametv-import-allhttp $Q --short-grab
#$d perl -I lib tools/nonametv-import Discovery_xml $Q
#tools/de/nonametv-import-allmail $Q

$d perl -I lib/ tools/nonametv-export Xmltv --remove-old
#$d perl -I lib/ tools/nonametv-export Json --remove-old
$d tools/nonametv-icon-update --quiet --unattended


# This shouldn't produce any output, but there seems to be a bug
# somewhere.
$d perl -I lib tools/nonametv-export Xmltv --force-export --verbose 

#tools/de/nonametv-updatesite $Q # not needed anymore
# Update the Downvonverter-channels as well.
$d perl -I lib tools/nonametv-import Downconverter $Q
$h perl -I lib tools/nonametv-import Downconverter --short-grab $Q

tools/de/nonametv-updatesite $Q
# Update the Combiner-channels as well.
$d perl -I lib tools/nonametv-import Combiner $Q
$h perl -I lib tools/nonametv-import Combiner --short-grab $Q

#tools/de/nonametv-updatesite $Q # not needed anymore
$d perl -I lib tools/nonametv-import Timeshifter $Q
$h perl -I lib tools/nonametv-import Timeshifter --short-grab $Q

perl -I lib tools/nonametv-batchlog > $NROOT/xmltv_staging/00status.html
tools/de/nonametv-updatesite $Q

$d tools/de/nonametv-xmltv-compare-run
perl -I lib tools/nonametv-batchlog > $NROOT/xmltv_compare/00status.html

