#!/bin/sh

NROOT=/home/nonametv/var
SC_OPT=-qq
V=false

if [ $1z = '--verbosez' ]
then
  SC_OPT=
  V=true
fi

# local rsync to keep last-modified timestamp unchanged if the file content is unchanged
$V && echo "Local rsync"
rsync -c --delete -r $NROOT/xmltv_staging/ $NROOT/xmltv/
tools/de/nonametv-xmltv-gendatalist
tools/nonametv-xmltv-gendvbservicepointer
tools/nonametv-xmltv-genlineup
#rsync -c --delete -r $NROOT/json_staging/ $NROOT/json/

#$V && echo "tv.swedb.se"
#sitecopy --update $SC_OPT tv.swedb.se

tools/nonametv-upload xmltv1
